#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import os.path


def configure(ctx):
    if ctx.env.WITH_STATIC_EXAMPLES:
        ctx.env.LINKFLAGS = ['-static', '-pthread']
        ctx.env.SHLIB_MARKER = '-Wl,-Bstatic'

        ctx.env.LIB = [ 'avformat', 'avcodec', 'avutil', 'xvidcore', 'x264',
                        'vorbis', 'vorbisenc', 'ogg', 'theora', 'speex',
                        'openjpeg', 'mp3lame', 'vpx', 'gsm', 'z', 'bz2' ]

def build(ctx):
    print('→ building from ' + ctx.path.abspath())
   
    jsonxx = ctx.stlib(
        source   = ctx.path.parent.ant_glob('3rdparty/jsonxx/jsonxx.cc'),
        target   = 'jsonxx',
        includes = [ '../3rdparty/jsonxx' ],
        use      = [],
        install_path = None
    )
        
    files = ['genVocab.cpp', 'rtlowleveldescriptors.cpp']
    ctx.program(
      source = ctx.path.ant_glob(' '.join(files)),
      target = 'genVocab',
      includes = ['.', '..'],
      use = 'essentia jsonxx ' + ctx.env.USES,
      install_path = None
    )
